name: "WakaTime - Profile Stats"
author: Barthachijuu
description: "Add a Wakatime Coding Activity graph in your Readme"

runs:
  using: "node12"
  main: "dist/index.js"

branding:
  icon: "info"
  color: "blue"