name: "WakaTime - Profile Stats"
author: Barthachijuu
description: "Add a Wakatime Coding Activity graph in your Readme"

inputs:
  GH_TOKEN:
    description: "GitHub access token with Repo scope"
    required: true

  WAKATIME_API_KEY:
    description: "Your Wakatime/Wakapi/Hakatime API Key"
    required: true

  API_BASE_URL:
    description: "Aternative API base URL when using a third-party WakaTime backend"
    default: "https://wakatime.com/api"
    required: false

  SHOW_TITLE:
    description: "Displays the week number and days in Readme as title"
    default: false
    required: false

  COMMIT_MESSAGE:
    description: "Add a commit message of your choice"
    default: "Updated the Graph with new Metrics"
    required: false

  BLOCKS:
    description: "Add the progress blocks of your choice"
    default: "░▒▓█"
    required: false

  SHOW_TIME:
    description: "Displays the amount of time spent in each language"
    default: true
    required: false

runs:
  using: "node12"
  main: "dist/index.js"

branding:
  icon: "info"
  color: "blue"