name: Update gist with WakaTime stats
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: barthachijuu/waka-profile-stats@feature/wakaApi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
